CREATE TABLE NOTAS (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  CLIENTE TEXT NOT NULL,
  VALOR_COMPRA DECIMAL(6,2) NOT NULL,
  DIA_COMPRA DATE NOT NULL DEFAULT (CURRENT_DATE),
  PRODUTO TEXT NOT NULL
);

INSERT INTO NOTAS VALUES (1, 'KAIQUE', 34.25, '2023-05-23', 'VIBRADOR MAX-PEN');

CREATE TABLE PRODUTOS (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NOME TEXT NOT NULL,
  VALOR DECIMAL(8,2) NOT NULL,
  VALIDADE TEXT NOT NULL,
  QNTD INTEGER NOT NULL,
  CREATED_AT DATE NOT NULL DEFAULT (CURRENT_DATE)
);

INSERT INTO PRODUTOS VALUES (1,'HEADSET', 259.99, 'NÃO APLICA', 50, '2023-05-23' );

CREATE TABLE MARCAS (
  ID INTEGER PRIMARY KEY,
  NOME TEXT NOT NULL,
  PRODUTOS_ID INTEGER,
  FOREIGN KEY (PRODUTOS_ID) REFERENCES PRODUTOS(ID)
);
INSERT INTO MARCAS VALUES (1, 'RAZER', 1);

SELECT PRODUTOS.NOME, PRODUTOS.VALOR, PRODUTOS.VALIDADE, MARCAS.NOME AS MARCA
FROM PRODUTOS
INNER JOIN MARCAS ON MARCAS.PRODUTOS_ID = PRODUTOS.ID;

SELECT PRODUTOS.NOME, PRODUTOS.VALOR, PRODUTOS.VALIDADE FROM PRODUTOS
INNER JOIN MARCAS ON MARCAS.PRODUTOS_ID = PRODUTOS.ID;


